dependencies:
  - name: nginx-ingress
    version: 1.28.2
    repository: https://charts.helm.sh/stable
    condition: nginx-ingress.enabled
  - name: rabbitmq
    version: 8.24.13
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled
  - name: solr
    version: 2.2.0
    repository: https://charts.bitnami.com/bitnami
    condition: solr.enabled
  - name: cassandra
    version: 9.1.0
    repository: https://charts.bitnami.com/bitnami
    condition: cassandra.enabled

